
name: Build & Deploy webapp 

env:
  ARTIFACT_NAME: csye6225-webapp-${{github.sha}}.zip
  CODEDEPLOY_APPLICATION_NAME: csye6225-webapp
  CODEDEPLOY_APPLICATION_NAME_GROUP_NAME: csye6225-webapp-deployment
  AWS_REGION: us-east-1
  aws_access_id: ${{secrets.PROD_AWS_ACCESS_KEY_ID}}
  aws_access_key: ${{secrets.PROD_AWS_ACCESS_KEY}}
  s3_bucket_name: ${{secrets.PROD_S3_CODEDEPLOY_BUCKET}}

on:
  pull_request:
    branches: [ main ]
    types: [closed]

jobs:
  ci_cd:
    if: github.event.pull_request.merged == true 
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2


    - name: Build Deployment Artifact
      run: |
        mkdir codedeploy_artifact 
        zip -r ${{env.ARTIFACT_NAME}} Server/* scripts/*.sh appspec.yml cloudwatch-config.json
        pwd
        ls -al 
        mv ${{env.ARTIFACT_NAME}} codedeploy_artifact/

    - name: Configure  AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{env.aws_access_id}}
        aws-secret-access-key: ${{env.aws_access_key}}
        aws-region: ${{env.AWS_REGION}}

    - name: Copy Artifact to S3
      run:
        aws s3 sync ./codedeploy_artifact s3://${{env.s3_bucket_name}}

    - name: Code deploy api call 
      run: |
        output=$(aws deploy create-deployment \
          --application-name ${{ env.CODEDEPLOY_APPLICATION_NAME}} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name ${{env.CODEDEPLOY_APPLICATION_NAME_GROUP_NAME}} \
          --description "CSYE6225 -CodeDeploy" \
          --s3-location bucket=${{env.s3_bucket_name}},key=${{env.ARTIFACT_NAME}},bundleType=zip \
          --region ${{env.AWS_REGION}} \
          --output json)

          echo $output

          dId=$(echo $output | jq -r '.deploymentId')

          aws deploy wait deployment-successful --deployment-id $dId

